[package]
name = "taskio"
version = "0.1.0"
edition = "2021"

[features]
generators = []
default = ["generators"]

[dependencies]
futures-util = { version = "0.3.28", default-features = false }
pin-project-lite = "0.2.9"
